version: '3'
services:
  app:
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - .:/ShareTask
    depends_on:
      - db
    command: bundle exec puma -C /ShareTask/config/puma.rb
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build:
      context: containers/nginx
    volumes:
      - .:/ShareTask
    ports:
      - 80:80
    depends_on:
      - app
