default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: share-task_development

test:
  <<: *default
  database: share-task_test

production:
  charset: utf8
  encoding: utf8
  adapter: mysql2
  pool: 5
  database: share-task_production
  username: share-task
  password: <%= ENV['SHARE-TASK_DATABASE_PASSWORD'] %>
